name = "claude-code-proxy"
main = "build/worker.mjs"
compatibility_date = "2022-05-13"
account_id = "02c07a2514d9a25f58c78a180bb8c6f3"
compatibility_flags = [
    "streams_enable_constructors"
]
kv_namespaces = [
  { binding = "claude_code_proxy_kv", id = "4f29ea2d933f4340b2ae3442c459e39f" }
]

[vars]
ENV = "production"


[build]
command = "just build-worker"
